### ISSUE TITLE
Treta ao tentar chamar bot sem nome do monstro

### ISSUE THREAD

**Issue by SirPedr** [SirPedr/LuckTheDuck#5]
Quando tenta chamar o `Luck` sem passar o nome do monstro, dá uma exceção no console e o bot não dá feedback =/
![image](https://user-images.githubusercontent.com/28637531/96198996-b84d8d80-0f2c-11eb-9e01-e14aa59a32bc.png)

**Comment by sauloviniciusf** [comment]
Quero fazer isso aqui

**Comment by SirPedr** [comment]
Resolvido em #11

**Comment by SirPedr** [comment]
Resolvido em #9
