### ISSUE TITLE
Fluxo de erros não está implementado corretamente

### ISSUE THREAD

**Issue by SirPedr** [SirPedr/LuckTheDuck#6]
Por conta da migração da API pra Open5e e dos `.catch()` que rolam no fluxo de pegar um monstro, a propagação de erros na árvore de execução tá zoando e ele não é propagado até chegar num ponto em que dê para mandar uam mensagem apropriada ao usuário. Seria bom revisar isso e garantir que a pilha não se perca do nada

**Comment by sauloviniciusf** [comment]
Pegando isso aqui

**Comment by SirPedr** [comment]
Resolvido em #11
