### ISSUE TITLE
Permitir buscar apenas propriedades específicas de um monstro

### ISSUE THREAD

**Issue by SirPedr** [SirPedr/LuckTheDuck#7]
Uma ideia legal seria permitir que a pessoa busque apenas os dados do monstro que lhe forem convenientes, em vez de receber tudo sobre ele toda vez. Talvez algo do tipo `!properties [nomeDasPropriedadesAqui]` seja suficiente. Daria pra deixar isso ser separado por vírgula ou algum outro caractere e fazer alguma normalização (tirando espaço e colocando em lowerCamelCase, por exemplo). Um exemplo seria:

`!luck angel !properties name;hit dice;actions` (A ordem dos comandos não deve ser importante)

**Comment by sauloviniciusf** [comment]
Trabalhando nisso

**Comment by SirPedr** [comment]
Resolvido em #12
